# Generated by Django 5.1.2 on 2024-10-19 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_booking_booking_now_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Phone_no', models.BigIntegerField()),
                ('Password', models.CharField(max_length=25)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Add_To_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.restaurent_menu_items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
    ]
