# Generated by Django 5.1.2 on 2024-10-21 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_now',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.customer'),
            preserve_default=False,
        ),
    ]
